name: Build with Hugo 0.159

on:
  push:
    branches:
      - new-hugo
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.159.0"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node dependencies
        run: npm ci

      - name: Build site
        run: hugo --minify --printPathWarnings --printI18nWarnings

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-0.159-site
          path: ./public
